apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cardcostapi-tls
  namespace: cardcostapi
spec:
  secretName: cardcostapi-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Your Organization
  commonName: cardcostapi.rndv-testing.xyz
  dnsNames:
    - cardcostapi.rndv-testing.xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
